//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class dv
    {
        public decimal n100 { get; set; }
        public Nullable<decimal> n101 { get; set; }
        public Nullable<decimal> n102 { get; set; }
        public Nullable<decimal> n103 { get; set; }
        public Nullable<decimal> n104 { get; set; }
        public Nullable<decimal> n105 { get; set; }
        public Nullable<decimal> n106 { get; set; }
        public Nullable<decimal> n107 { get; set; }
        public Nullable<decimal> n108 { get; set; }
        public Nullable<decimal> n109 { get; set; }
        public string s100 { get; set; }
        public string s101 { get; set; }
        public string s102 { get; set; }
        public string s103 { get; set; }
        public string s104 { get; set; }
        public string s105 { get; set; }
        public string s106 { get; set; }
        public string s107 { get; set; }
        public string s108 { get; set; }
        public string s109 { get; set; }
        public Nullable<System.DateTime> d100 { get; set; }
        public Nullable<System.DateTime> d101 { get; set; }
        public Nullable<System.DateTime> d102 { get; set; }
        public Nullable<System.DateTime> d103 { get; set; }
        public Nullable<System.DateTime> d104 { get; set; }
        public string s1 { get; set; }
        public string s2 { get; set; }
        public string s3 { get; set; }
        public string s4 { get; set; }
        public string s5 { get; set; }
        public string s6 { get; set; }
        public string s7 { get; set; }
        public string s8 { get; set; }
        public string s9 { get; set; }
        public string s10 { get; set; }
        public string s11 { get; set; }
        public string s12 { get; set; }
        public string s13 { get; set; }
        public string s14 { get; set; }
        public string s15 { get; set; }
        public string s16 { get; set; }
        public string s17 { get; set; }
        public string s18 { get; set; }
        public string s19 { get; set; }
        public string s20 { get; set; }
        public string s21 { get; set; }
        public string s22 { get; set; }
        public string s23 { get; set; }
        public string s24 { get; set; }
        public string s25 { get; set; }
        public string s26 { get; set; }
        public string s27 { get; set; }
        public string s28 { get; set; }
        public string s29 { get; set; }
        public string s30 { get; set; }
        public string s31 { get; set; }
        public string s32 { get; set; }
        public string s33 { get; set; }
        public string s34 { get; set; }
        public string s35 { get; set; }
        public string s36 { get; set; }
        public string s37 { get; set; }
        public string s38 { get; set; }
        public string s39 { get; set; }
        public string s40 { get; set; }
        public Nullable<decimal> n1 { get; set; }
        public Nullable<decimal> n2 { get; set; }
        public Nullable<decimal> n3 { get; set; }
        public Nullable<decimal> n4 { get; set; }
        public Nullable<decimal> n5 { get; set; }
        public Nullable<decimal> n6 { get; set; }
        public Nullable<decimal> n7 { get; set; }
        public Nullable<decimal> n8 { get; set; }
        public Nullable<decimal> n9 { get; set; }
        public Nullable<decimal> n10 { get; set; }
        public Nullable<decimal> n11 { get; set; }
        public Nullable<decimal> n12 { get; set; }
        public Nullable<decimal> n13 { get; set; }
        public Nullable<decimal> n14 { get; set; }
        public Nullable<decimal> n15 { get; set; }
        public Nullable<decimal> n16 { get; set; }
        public Nullable<decimal> n17 { get; set; }
        public Nullable<decimal> n18 { get; set; }
        public Nullable<decimal> n19 { get; set; }
        public Nullable<decimal> n20 { get; set; }
        public Nullable<System.DateTime> d1 { get; set; }
        public Nullable<System.DateTime> d2 { get; set; }
        public Nullable<System.DateTime> d3 { get; set; }
        public Nullable<System.DateTime> d4 { get; set; }
        public Nullable<System.DateTime> d5 { get; set; }
        public Nullable<System.DateTime> d6 { get; set; }
        public Nullable<System.DateTime> d7 { get; set; }
        public Nullable<System.DateTime> d8 { get; set; }
        public Nullable<System.DateTime> d9 { get; set; }
        public Nullable<System.DateTime> d10 { get; set; }
    }
}
