//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class dvcombo
    {
        public decimal n100 { get; set; }
        public Nullable<decimal> n101 { get; set; }
        public string s100 { get; set; }
        public string s101 { get; set; }
        public string s102 { get; set; }
        public string s108 { get; set; }
        public string s1 { get; set; }
        public string s2 { get; set; }
        public Nullable<System.DateTime> d1 { get; set; }
        public string s3 { get; set; }
    }
}
